// Command gensetup derives runtime-efficient KZG parameters from the exact
// go-kzg dependency pinned by this module. Generated assets are committed so
// normal builds never read the module cache or the upstream JSON setup.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"math/bits"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	bls12381 "github.com/consensys/gnark-crypto/ecc/bls12-381"
)

const (
	setupModulePath    = "github.com/crate-crypto/go-kzg-4844"
	setupModuleVersion = "v1.1.0"
	setupSourceSHA256  = "0229b43f4fac9b17374809520eb621b5ee1a7f74547e7d36918e7d4b122e178d"
	setupWidth         = 4096
)

type moduleInfo struct {
	Path    string      `json:"Path"`
	Version string      `json:"Version"`
	Dir     string      `json:"Dir"`
	Replace *moduleInfo `json:"Replace"`
}

type trustedSetup struct {
	G1Lagrange []string `json:"g1_lagrange"`
	G2Monomial []string `json:"g2_monomial"`
}

func main() {
	verifierOut := flag.String("verifier-out", "trusted_setup_verifier.bin", "minimal verifier setup output")
	writerOut := flag.String("writer-out", "trusted_setup_writer.bin", "preprocessed writer setup output")
	goOut := flag.String("go-out", "trusted_setup_generated.go", "generated fingerprint constants")
	flag.Parse()

	verifier, writer, err := generateFromPinnedModule()
	check(err)
	check(writeAtomic(*verifierOut, verifier))
	check(writeAtomic(*writerOut, writer))
	verifierSum := sha256.Sum256(verifier)
	writerSum := sha256.Sum256(writer)
	generated := fmt.Sprintf(`// Code generated by go generate; DO NOT EDIT.

package kzg

const (
	trustedSetupModuleVersion = %q
	trustedSetupSourceSHA256 = %q
	trustedSetupVerifierSHA256 = %q
	trustedSetupWriterSHA256 = %q
)
`, setupModuleVersion, setupSourceSHA256, hex.EncodeToString(verifierSum[:]), hex.EncodeToString(writerSum[:]))
	formatted, err := format.Source([]byte(generated))
	check(err)
	check(writeAtomic(*goOut, formatted))
}

func generateFromPinnedModule() ([]byte, []byte, error) {
	module, err := locateSetupModule()
	if err != nil {
		return nil, nil, err
	}
	source, err := os.ReadFile(filepath.Join(module.Dir, "trusted_setup.json"))
	if err != nil {
		return nil, nil, fmt.Errorf("read trusted setup: %w", err)
	}
	sourceSum := sha256.Sum256(source)
	if got := hex.EncodeToString(sourceSum[:]); got != setupSourceSHA256 {
		return nil, nil, fmt.Errorf("trusted setup source SHA-256 %s, want %s", got, setupSourceSHA256)
	}

	var setup trustedSetup
	if err := json.Unmarshal(source, &setup); err != nil {
		return nil, nil, fmt.Errorf("decode trusted setup: %w", err)
	}
	return deriveAssets(setup)
}

func deriveAssets(setup trustedSetup) ([]byte, []byte, error) {
	if len(setup.G1Lagrange) != setupWidth {
		return nil, nil, fmt.Errorf("trusted setup has %d Lagrange G1 points, want %d", len(setup.G1Lagrange), setupWidth)
	}
	if len(setup.G2Monomial) < 2 {
		return nil, nil, fmt.Errorf("trusted setup has %d G2 points, want at least 2", len(setup.G2Monomial))
	}

	verifier := make([]byte, 0, 2*bls12381.SizeOfG2AffineCompressed)
	for i := 0; i < 2; i++ {
		encoded, err := decodeHex(setup.G2Monomial[i])
		if err != nil {
			return nil, nil, fmt.Errorf("decode G2 point %d: %w", i, err)
		}
		var point bls12381.G2Affine
		_, err = point.SetBytes(encoded)
		if err != nil { // SetBytes performs curve and subgroup checks.
			return nil, nil, fmt.Errorf("validate G2 point %d: %w", i, err)
		}
		normalized := point.Bytes()
		verifier = append(verifier, normalized[:]...)
	}

	points := make([]bls12381.G1Affine, setupWidth)
	for i, encodedPoint := range setup.G1Lagrange {
		encoded, err := decodeHex(encodedPoint)
		if err != nil {
			return nil, nil, fmt.Errorf("decode G1 point %d: %w", i, err)
		}
		_, err = points[i].SetBytes(encoded)
		if err != nil { // Validate every source point before preprocessing it.
			return nil, nil, fmt.Errorf("validate G1 point %d: %w", i, err)
		}
	}
	bitReverse(points)
	writer := make([]byte, 0, setupWidth*bls12381.SizeOfG1AffineUncompressed)
	for i := range points {
		raw := points[i].RawBytes()
		writer = append(writer, raw[:]...)
	}

	return verifier, writer, nil
}

func locateSetupModule() (moduleInfo, error) {
	output, err := exec.Command("go", "list", "-m", "-json", setupModulePath).Output()
	if err != nil {
		return moduleInfo{}, fmt.Errorf("locate %s: %w", setupModulePath, err)
	}
	var module moduleInfo
	if err := json.Unmarshal(output, &module); err != nil {
		return moduleInfo{}, fmt.Errorf("decode module metadata: %w", err)
	}
	if module.Path != setupModulePath || module.Version != setupModuleVersion || module.Dir == "" {
		return moduleInfo{}, fmt.Errorf("resolved %s@%s in %q, want %s@%s", module.Path, module.Version, module.Dir, setupModulePath, setupModuleVersion)
	}
	if module.Replace != nil {
		return moduleInfo{}, fmt.Errorf("refusing replaced setup module %s@%s", module.Replace.Path, module.Replace.Version)
	}
	return module, nil
}

func decodeHex(value string) ([]byte, error) {
	if !strings.HasPrefix(value, "0x") {
		return nil, fmt.Errorf("trusted setup point is missing 0x prefix")
	}
	encoded, err := hex.DecodeString(value[2:])
	if err != nil {
		return nil, fmt.Errorf("decode trusted setup point: %w", err)
	}
	return encoded, nil
}

func bitReverse[T any](values []T) {
	shift := uint(bits.UintSize - bits.TrailingZeros(uint(len(values))))
	for i := range values {
		j := int(bits.Reverse(uint(i)) >> shift)
		if j > i {
			values[i], values[j] = values[j], values[i]
		}
	}
}

func writeAtomic(path string, data []byte) error {
	dir := filepath.Dir(path)
	temporary, err := os.CreateTemp(dir, ".malt-kzg-setup-*")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(0o644); err != nil {
		temporary.Close()
		return err
	}
	if _, err := temporary.Write(data); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(temporaryPath, path)
}

func check(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
